// CONFIG 领域注册
Object.assign(CONFIG, {  // 上下各4行 + 中间1行路 = 9行

  TOWERS: {
    fire: {
      char: "火",
      cost: 120,
      damage: 1.1,
      range: 4.2,
      cooldown: 900,
      upgradeCost: 60,
      maxLevel: 3,
      desc: "发射旋转的火字追踪导弹",
      upgradeParams: { damageInc: 1, rangeInc: 0.5, cooldownDec: 100 },
    },
    water: {
      char: "水",
      cost: 100,
      damage: 0,
      range: 3.2,
      cooldown: 750,
      slow: 0.45,
      slowDuration: 2800,
      upgradeCost: 45,
      maxLevel: 3,
      desc: "延缓敌人移动速度45%",
      upgradeParams: { rangeInc: 1, cooldownDec: 100, slowInc: 0.1 },
    },
    mountain: {
      char: "山",
      cost: 150,
      hp: 22,
      damage: 1.8,
      upgradeCost: 70,
      maxLevel: 3,
      onPath: true,
      desc: "放置在路径上阻挡敌人并反伤",
      upgradeParams: { hpInc: 2, damageInc: 1 },
    },
    wood: {
      char: "木",
      cost: 105,
      damage: 0.45,
      range: 4.0,
      cooldown: 380,
      upgradeCost: 50,
      maxLevel: 3,
      unlockLevel: 2,
      desc: "快速连射",
      upgradeParams: { damageInc: 1, rangeInc: 0.5, cooldownDec: 100 },
    },
    gold: {
      char: "金",
      cost: 190,
      damage: 3.2,
      range: 7.5,
      cooldown: 1650,
      pierce: true,
      upgradeCost: 90,
      maxLevel: 3,
      unlockLevel: 3,
      desc: "直线穿透攻击",
      upgradeParams: { damageInc: 1, rangeInc: 0.5, cooldownDec: 100 },
    },
    earth: {
      char: "土",
      cost: 230,
      damage: 2.8,
      range: 3.2,
      cooldown: 1550,
      aoe: true,
      aoeRange: 2.2,
      upgradeCost: 110,
      maxLevel: 3,
      unlockLevel: 4,
      desc: "范围AOE伤害",
      upgradeParams: { damageInc: 1, rangeInc: 0.5, cooldownDec: 100 },
    },
    xinZhongYan: {
      char: "心中炎",
      cost: 260,
      damage: 3.2,
      range: 6.0,
      cooldown: 1450,
      burn: true,
      burnDuration: 3200,
      burnDamage: 1.2,
      upgradeCost: 120,
      maxLevel: 3,
      unlockLevel: 5,
      desc: "心火攻击，高伤害带灼烧",
      upgradeParams: { damageInc: 1, rangeInc: 0.5, cooldownDec: 100 },
    },
    ruFengSiZhen: {
      char: "如风似真",
      cost: 310,
      damage: 2.6,
      range: 5.2,
      cooldown: 1100,
      chain: true,
      chainCount: 4,
      chainRange: 160,
      upgradeCost: 150,
      maxLevel: 3,
      unlockLevel: 6,
      desc: "风链弹射，攻击在敌人间弹跳",
      upgradeParams: { damageInc: 1, rangeInc: 0.5, cooldownDec: 100 },
    },
    thunder: {
      char: '雷',
      cost: 210,
      damage: 2.1,
      range: 5.2,
      cooldown: 1150,
      chain: true,
      chainCount: 3,
      chainRange: 180,
      chainDecay: 0.23,
      conductBonus: 1.5,
      upgradeCost: 100,
      maxLevel: 3,
      unlockLevel: 4,
      desc: '雷电弹射，对灼烧/潮湿敌人伤害加成',
      upgradeParams: { damageInc: 0.6, rangeInc: 0.5, cooldownDec: 140, chainCountInc: 1 },
    },
    ice: {
      char: '冰',
      cost: 170,
      damage: 1.1,
      range: 4.2,
      cooldown: 850,
      slow: 0.38,
      slowDuration: 2500,
      freezeDuration: 1200,
      freezeCooldown: 8000,
      upgradeCost: 80,
      maxLevel: 3,
      unlockLevel: 3,
      desc: '减速敌人并触发冻结',
      upgradeParams: { damageInc: 0.24, rangeInc: 0.5, cooldownDec: 100, slowInc: 0.1, freezeDurationInc: 300 },
    },
    poison: {
      char: '毒',
      cost: 180,
      damage: 0.8,
      range: 4.2,
      cooldown: 650,
      poisonDamage: 0.35,
      poisonDuration: 4200,
      poisonStackMax: 5,
      ulcerDuration: 5000,
      upgradeCost: 85,
      maxLevel: 3,
      unlockLevel: 5,
      desc: '叠加毒层，3层触发溃烂破甲',
      upgradeParams: { damageInc: 0.15, rangeInc: 0.5, cooldownDec: 70, poisonDamageInc: 0.1, ulcerDurationInc: 1000 },
    },
    wind: {
      char: '风',
      cost: 185,
      damage: 1.4,
      range: 5.2,
      cooldown: 1000,
      knockback: 1.2,
      knockbackCooldown: 2800,
      dispel: true,
      upgradeCost: 90,
      maxLevel: 3,
      unlockLevel: 5,
      desc: '击退敌人并清除增益',
      upgradeParams: { damageInc: 0.36, rangeInc: 0.5, cooldownDec: 110, knockbackInc: 0.5 },
    },
    light: {
      char: '光',
      cost: 200,
      damage: 1.7,
      range: 6.2,
      cooldown: 1050,
      pierce: true,
      pierceCount: 2,
      revealDuration: 4500,
      revealBonus: 1.8,
      upgradeCost: 95,
      maxLevel: 3,
      unlockLevel: 6,
      desc: '显形隐身敌人，穿透攻击',
      upgradeParams: { damageInc: 0.45, rangeInc: 0.5, cooldownDec: 120, pierceCountInc: 1, revealDurationInc: 1000 },
    },
    dark: {
      char: '暗',
      cost: 240,
      damage: 2.4,
      range: 5.2,
      cooldown: 1200,
      killHeal: 1.2,
      shadowMarkDuration: 5000,
      shadowMarkBonusHeal: 1,
      healPerWaveMax: 12,
      upgradeCost: 115,
      maxLevel: 3,
      unlockLevel: 7,
      desc: '击杀敌人回复核心HP',
      upgradeParams: { damageInc: 0.66, rangeInc: 0.5, cooldownDec: 130, killHealInc: 1 },
    },
    star: {
      char: '星',
      cost: 270,
      damage: 2.2,
      range: 5.2,
      cooldown: 900,
      elementChances: { fire: 0.3, water: 0.25, thunder: 0.2, ice: 0.25 },
      comboBonus: 0.35,
      upgradeCost: 130,
      maxLevel: 3,
      unlockLevel: 8,
      desc: '随机元素攻击，连击加成',
      upgradeParams: { damageInc: 0.54, rangeInc: 0.5, cooldownDec: 100, comboBonusInc: 0.1 },
    },
    frost: {
      char: '霜',
      cost: 250,
      damage: 2.6,
      range: 3.2,
      cooldown: 1450,
      aoe: true,
      aoeRange: 2.2,
      frostSlow: 0.30,
      frostSlowDuration: 2000,
      deepColdBonus: 2.0,
      frostGroundDuration: 3000,
      upgradeCost: 120,
      maxLevel: 3,
      unlockLevel: 7,
      desc: '范围冰霜，对冰冻敌人双倍伤害',
      upgradeParams: { damageInc: 0.6, rangeInc: 0.5, cooldownDec: 180, aoeRangeInc: 0.5, frostSlowInc: 0.05 },
    },
    drum: {
      char: '鼓',
      cost: 155,
      damage: 0,
      range: 0,
      cooldown: 0,
      aura: true,
      auraRange: 3.2,
      auraType: 'attackSpeed',
      auraValue: 0.18,
      upgradeCost: 75,
      maxLevel: 3,
      unlockLevel: 4,
      desc: '为范围内炮塔提供攻速加成',
      upgradeParams: { auraRangeInc: 0.5, auraValueInc: 0.08 },
    },
    banner: {
      char: '旗',
      cost: 140,
      damage: 0,
      range: 0,
      cooldown: 0,
      aura: true,
      auraRange: 4.2,
      auraType: 'range',
      auraValue: 1.1,
      upgradeCost: 65,
      maxLevel: 3,
      unlockLevel: 5,
      desc: '为范围内炮塔提供射程加成',
      upgradeParams: { auraRangeInc: 0.5, auraValueInc: 0.5 },
    },
    bell: {
      char: '钟',
      cost: 210,
      damage: 1.2,
      range: 3.5,
      cooldown: 2200,
      stunDuration: 1200,
      stunRange: 3.2,
      upgradeCost: 100,
      maxLevel: 3,
      unlockLevel: 6,
      desc: '周期性眩晕范围内敌人',
      upgradeParams: { damageInc: 0.15, rangeInc: 0.5, cooldownDec: 300, stunDurationInc: 300 },
    },
    mirror: {
      char: '镜',
      cost: 190,
      damage: 0,
      range: 0,
      cooldown: 0,
      aura: true,
      auraRange: 3.2,
      auraType: 'reflect',
      auraValue: 0.32,
      mountainBonus: 0.6,
      upgradeCost: 90,
      maxLevel: 3,
      unlockLevel: 7,
      desc: '为范围内炮塔提供伤害反射',
      upgradeParams: { auraRangeInc: 0.5, auraValueInc: 0.1, mountainBonusInc: 0.15 },
    },
    zither: {
      char: '琴',
      cost: 170,
      damage: 0,
      range: 0,
      cooldown: 0,
      aura: true,
      auraRange: 3.2,
      auraType: 'slow',
      auraValue: 0.24,
      upgradeCost: 80,
      maxLevel: 3,
      unlockLevel: 5,
      desc: '减速范围内所有敌人',
      upgradeParams: { auraRangeInc: 0.5, auraValueInc: 0.08 },
    },
    talisman: {
      char: '符',
      cost: 150,
      damage: 0.9,
      range: 5.2,
      cooldown: 1200,
      markDuration: 5500,
      markBonus: 0.35,
      markCount: 2,
      upgradeCost: 70,
      maxLevel: 3,
      unlockLevel: 6,
      desc: '标记敌人使其受到伤害增加',
      upgradeParams: { rangeInc: 0.5, cooldownDec: 150, markDurationInc: 1000, markBonusInc: 0.1, markCountInc: 1 },
    },
    formation: {
      char: '阵',
      cost: 220,
      damage: 0,
      range: 0,
      cooldown: 0,
      aura: true,
      auraRange: 2.2,
      auraType: 'dot',
      auraValue: 0.9,
      auraSlow: 0.22,
      upgradeCost: 105,
      maxLevel: 3,
      unlockLevel: 8,
      desc: '阵法范围内持续伤害并减速',
      upgradeParams: { auraRangeInc: 0.5, auraValueInc: 0.3, auraSlowInc: 0.05 },
    },
    lantern: {
      char: '灯',
      cost: 130,
      damage: 0,
      range: 0,
      cooldown: 0,
      aura: true,
      auraRange: 4.2,
      auraType: 'reveal',
      auraValue: 0.18,
      upgradeCost: 60,
      maxLevel: 3,
      unlockLevel: 6,
      desc: '照明范围内隐身敌人显形',
      upgradeParams: { auraRangeInc: 0.5, auraValueInc: 0.05 },
    },
    wall: {
      char: '壁',
      cost: 190,
      hp: 42,
      damage: 0,
      onPath: true,
      repairRatio: 0.55,
      upgradeCost: 90,
      maxLevel: 3,
      unlockLevel: 5,
      desc: '高HP路径阻挡塔',
      upgradeParams: { hpInc: 15, repairRatioInc: 0.1 },
    },
    moat: {
      char: '壕',
      cost: 120,
      hp: 14,
      damage: 0.35,
      range: 0,
      cooldown: 0,
      slow: 0.38,
      slowDuration: 3200,
      onPath: true,
      upgradeCost: 55,
      maxLevel: 3,
      unlockLevel: 4,
      desc: '路径减速陷阱',
      upgradeParams: { hpInc: 6, slowInc: 0.08, slowDurationInc: 500, damageInc: 0.1 },
    },
    trap: {
      char: '陷',
      cost: 170,
      hp: 10,
      damage: 6.0,
      range: 0,
      cooldown: 0,
      stunDuration: 1700,
      triggerCount: 4,
      maxTriggers: 4,
      onPath: true,
      upgradeCost: 80,
      maxLevel: 3,
      unlockLevel: 7,
      desc: '触发式陷阱，造成大量伤害并眩晕',
      upgradeParams: { hpInc: 4, damageInc: 1.5, stunDurationInc: 500, triggerCountInc: 1 },
    },
    arrow: {
      char: '箭',
      cost: 180,
      hp: 12,
      damage: 1.1,
      range: 3.2,
      cooldown: 600,
      pierce: true,
      pierceCount: 1,
      onPath: true,
      upgradeCost: 80,
      maxLevel: 3,
      unlockLevel: 5,
      desc: '路径上自动攻击的箭塔',
      upgradeParams: { hpInc: 6, damageInc: 0.3, rangeInc: 0.5, cooldownDec: 60 },
    },
    bunker: {
      char: '碉',
      cost: 300,
      hp: 34,
      damage: 2.4,
      range: 2.2,
      cooldown: 1100,
      reflectDamage: 2.6,
      damageReduction: 0.22,
      onPath: true,
      upgradeCost: 140,
      maxLevel: 3,
      unlockLevel: 8,
      desc: '重型堡垒，攻防一体',
      upgradeParams: { hpInc: 12, damageInc: 0.6, reflectDamageInc: 0.6, damageReductionInc: 0.05 },
    },
    palisade: {
      char: '栅',
      cost: 80,
      hp: 8,
      damage: 0.6,
      onPath: true,
      repairRatio: 0.35,
      upgradeCost: 35,
      maxLevel: 3,
      unlockLevel: 2,
      desc: '低费路径路障',
      upgradeParams: { hpInc: 4, damageInc: 0.2, repairRatioInc: 0.1 },
    },
    treasure: {
      char: '财',
      cost: 110,
      damage: 0,
      range: 0,
      cooldown: 0,
      inkPerWave: 30,
      interestInterval: 3,
      interestBonus: 6,
      maxCount: 2,
      upgradeCost: 50,
      maxLevel: 3,
      unlockLevel: 3,
      desc: '每波产出生息墨水',
      upgradeParams: { inkPerWaveInc: 10, interestBonusInc: 3 },
    },
    healer: {
      char: '医',
      cost: 160,
      damage: 0,
      range: 0,
      cooldown: 0,
      healPerWave: 4,
      emergencyThreshold: 0.35,
      emergencyBonus: 2.5,
      maxCount: 1,
      upgradeCost: 75,
      maxLevel: 3,
      unlockLevel: 5,
      desc: '每波回复核心HP',
      upgradeParams: { healPerWaveInc: 2, emergencyBonusInc: 1 },
    },
    soul: {
      char: '魂',
      cost: 230,
      damage: 0,
      range: 4.2,
      cooldown: 7500,
      summonHp: 6,
      summonDamage: 1.2,
      summonDuration: 10000,
      maxSummons: 2,
      upgradeCost: 110,
      maxLevel: 3,
      unlockLevel: 7,
      desc: '召唤灵魂守卫',
      upgradeParams: { cooldownDec: 1000, summonHpInc: 3, summonDamageInc: 0.3, maxSummonsInc: 1 },
    },
    shadow: {
      char: '影',
      cost: 210,
      damage: 0,
      range: 0,
      cooldown: 0,
      copyEfficiency: 0.58,
      upgradeCost: 100,
      maxLevel: 3,
      unlockLevel: 8,
      desc: '复制相邻炮塔的攻击',
      upgradeParams: { copyEfficiencyInc: 0.15 },
    },
    time: {
      char: '时',
      cost: 320,
      damage: 0,
      range: 0,
      cooldown: 0,
      globalSlow: 0.18,
      upgradeCost: 150,
      maxLevel: 3,
      unlockLevel: 9,
      desc: '减缓全局时间流速',
      upgradeParams: { globalSlowInc: 0.07 },
    },
    detonator: {
      char: '爆',
      cost: 130,
      damage: 9.0,
      range: 3.2,
      cooldown: 0,
      explodeRange: 3.2,
      stunDuration: 1200,
      isDetonator: true,
      upgradeCost: 60,
      maxLevel: 3,
      unlockLevel: 6,
      desc: '手动引爆，大范围伤害后销毁',
      upgradeParams: { damageInc: 3.0, explodeRangeInc: 0.5, stunDurationInc: 500 },
    },
    parasite: {
      char: '蛊',
      cost: 200,
      damage: 1.1,
      range: 4.2,
      cooldown: 800,
      parasiteDuration: 6500,
      explosionDamage: 3.5,
      explosionRange: 2,
      upgradeCost: 95,
      maxLevel: 3,
      unlockLevel: 8,
      desc: '寄生敌人，死亡时爆炸',
      upgradeParams: { damageInc: 0.24, rangeInc: 0.5, cooldownDec: 90, explosionDamageInc: 1.0, explosionRangeInc: 0.5 },
    },
    wheel: {
      char: '轮',
      cost: 240,
      damage: 1.2,
      range: 4.8,
      cooldown: 500,
      rotationSpeed: 66,
      fanAngle: 34,
      upgradeCost: 100,
      maxLevel: 3,
      unlockLevel: 7,
      desc: '旋转扫射攻击',
      upgradeParams: { damageInc: 0.45, rangeInc: 0.5, rotationSpeedInc: 12, fanAngleInc: 10 },
    },
    fusion: {
      char: "融合",
      cost: 0,
      damage: 0,
      range: 0,
      cooldown: 1000,
      maxLevel: 1,
      desc: "融合炮塔基类",
    },
  },
});
